import type { NextPage } from "next";
import Head from "next/head";
import Experience from "../components/Experience";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

const Home: NextPage = () => {
  return (
    <div className='pb-96 bg-gradient-to-br from-[#010519] via-[#010722] to-[#0f1e3f] text-blue-50 tracking-wide'>
      <Head>
        <title>Ahmad Alghali Portfolio</title>
        {/* <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' /> */}
      </Head>

      <Header />

      <Hero />

      <div className='mt-20 container mx-auto px-5  space-y-32'>
        <Skills />

        <Experience />

        <Projects />
      </div>

      {/* About */}
      {/* Contact me */}
      {/* <ContactMe /> */}
    </div>
  );
};

export default Home;
